name: Git Blame Ignore

on:
  schedule:
    - cron: "45 21 * * *" # Runs daily at 22:00 UTC
  workflow_dispatch:

jobs:
  blame-ignore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Needed to bypass protection rules in Push changes

      - name: Download last checked commit artifact
        id: download_artifact
        uses: actions/download-artifact@v4.1.8
        continue-on-error: true
        with:
          name: artifact-last-blame-ignore-commit

      - name: Get last checked commit
        id: get_last_commit
        run: |
          if [ -f last-blame-ignore-commit ]; then
            LAST_CHECKED_COMMIT=$(cat last-blame-ignore-commit)
          else
            LAST_CHECKED_COMMIT=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "LAST_CHECKED_COMMIT=$LAST_CHECKED_COMMIT" >> $GITHUB_ENV

      - name: Process commits and update blame ignore list
        run: |
          git log ${{ env.LAST_CHECKED_COMMIT }}..HEAD --pretty=format:"%H %s" --grep="\[blame ignore\]" | awk '{print $1}' >> .git-blame-ignore-revs

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git rev-parse HEAD > last-blame-ignore-commit

          git add .git-blame-ignore-revs
          git commit -m "chore: auto blame ignore" -m "[skip changelog]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.MAA_RESOURCE_SYNC }}

      - name: Upload last checked commit artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-last-blame-ignore-commit
          path: last-blame-ignore-commit
          retention-days: 90 # Default retention period for artifacts
